extern "C"
{
 unsigned char __declspec(dllimport) _cdecl _DrukRap(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _DrukRapD(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _KDBarkod(char* in);
 unsigned char __declspec(dllimport) _cdecl _KDBarMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _KDefKlaw(char* in);
 unsigned char __declspec(dllimport) _cdecl _KDefKMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _KEStDef(char* in);
 unsigned char __declspec(dllimport) _cdecl _KEStDMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _KEStTMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _KEStTow(char* in);
 unsigned char __declspec(dllimport) _cdecl _KGrupa(char* in);
 unsigned char __declspec(dllimport) _cdecl _KGrupMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _KKasjer(char* in);
 unsigned char __declspec(dllimport) _cdecl _KKlawisz(char* in);
 unsigned char __declspec(dllimport) _cdecl _KSDBaMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _KSprawdz(char* in);
 unsigned char __declspec(dllimport) _cdecl _KSprOp(char* in);
 unsigned char __declspec(dllimport) _cdecl _KSTowar(char* in);
 unsigned char __declspec(dllimport) _cdecl _KSTowMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _KSzufMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _KTBarkod(char* in);
 unsigned char __declspec(dllimport) _cdecl _KTowar(char* in);
 unsigned char __declspec(dllimport) _cdecl _KTowMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _KTWaga(char* in);
 unsigned char __declspec(dllimport) _cdecl _KTWagMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _KuchDruk(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _KWaluta(char* in);
 unsigned char __declspec(dllimport) _cdecl _KWiaz(char* in);
 unsigned char __declspec(dllimport) _cdecl _ModHaslo(char* in);
 unsigned char __declspec(dllimport) _cdecl _ModIlDzw(char* in);
 unsigned char __declspec(dllimport) _cdecl _ModNrWer(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ModStart(char* in);
 unsigned char __declspec(dllimport) _cdecl _ModStop(char* in);
 unsigned char __declspec(dllimport) _cdecl _OBajtMax(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OBajty(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OBarPods(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OBarTow(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ODaneARG(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ODanePRG(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ODaneRek(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ODaneUz(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ODataARG(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ODataPRG(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ODBajty(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ODBarkod(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ODefKlaw(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ODKBajty(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ODNBajty(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ODSprzed(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OEStDef(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OEStDMax(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OEStTMax(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OEStTow(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OEtyk(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OGrupa(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OHalo(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OIKas(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OIKasOtw(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OIKasWla(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OIKasZam(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OIKasZZ(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OIlZaPLU(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OJednost(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OKartRab(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OKasjer(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OKlawisz(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OKRabMax(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OKSprzed(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OLinia(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ONarzut(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ONKasWla(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ONNazwa(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ONrDodPa(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ONrKasy(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ONrParag(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ONrRap(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ONrRekor(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ONrSpraw(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ONrTowar(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ONrUnik(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OObrRab(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OOpak(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OOSprzed(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OPBarkod(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OPlat(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OPodatek(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OPojemn(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OPSpRoz(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OPSpRozN(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OPSpRozX(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OPSprzed(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ORabat(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ORabNPod(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OSBajty(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OSJednos(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OSpOpMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _OSprzed(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OSprzPod(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OSPBarko(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OSReklam(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OStatus(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OSTowar(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OSTowMax(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OSygPara(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OSzufMax(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OTowar(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OTPojemn(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OTSpMax(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OTSprzed(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OTWaga(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OTWagMax(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OTypUrz(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OUprKas(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OWaluta(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OWersja(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OWiaz(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OWiersz(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _OZegar(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _Paker(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _PoSekwSt(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _PoslPlik(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _RekorMax(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _RSTest(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _Sorter(char* in);
 unsigned char __declspec(dllimport) _cdecl _SortPak(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _TowarMax(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _WyplGot(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZBajtMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZBajty(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZBlok(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZBPTowar(char* in, char* out);
 unsigned char __declspec(dllimport) _cdecl _ZCTowar(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZDataAkt(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZDBajty(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZDBarkod(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZDefKlaw(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZDKBajty(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZDNBajty(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZDSprzed(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZEStDef(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZEStTow(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZGrupa(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZHalo(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZJednost(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZKartRab(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZKasjer(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZKlawisz(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZKRabMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZLinia(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZNarzut(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZNrKasy(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZNrDodPa(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZNrSpraw(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZPBarkod(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZPlat(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZPojemn(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZRabat(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZSBajty(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZSBlok(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZSJednos(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZSPBarko(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZSReklam(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZSTowar(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZSygPara(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZSzufMax(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZTowar(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZTPojemn(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZTWaga(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZUprKas(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZWaluta(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZWiaz(char* in);
 unsigned char __declspec(dllimport) _cdecl _ZWiersz(char* in);
}